/*
 * generated by Xtext 2.24.0
 */
package dk.sdu.tamamo;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ModuleTreeStandaloneSetup extends ModuleTreeStandaloneSetupGenerated {

	public static void doSetup() {
		new ModuleTreeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
